name: A workflow for my Hello World App
on: push

jobs:
  build:
    name: Hello world action
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Setup network
        run: |
          docker network create --driver bridge ce-methods
          docker pull mongo
          docker run -d --name mongo-dbserver --network ce-methods mongo
      - name: Build with Maven
        run: mvn package
      - name: Build
        run: docker build -t ce_methods .
      - name: Run image
        run: docker run --network ce-methods --name semcontainer ce_methods
      - name: view logs
        run: docker logs semcontainer